---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    k8s.kuboard.cn/name: mysql-diff
  name: mysql-diff
  namespace: ops
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        k8s.kuboard.cn/name: mysql-diff
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - env:
                - name: PROD_DB_HOST
                  value: host
                - name: PROD_DB_USER
                  value: user
                - name: PROD_DB_PASSWORD
                  value: pass
                - name: PROD_DB_NAME
                  value: db
                - name: TEST_DB_HOST
                  value: host
                - name: TEST_DB_USER
                  value: user
                - name: TEST_DB_PASSWORD
                  value: pass
                - name: TEST_DB_NAME
                  value: db
                - name: FEISHU_RECEIVE_ID
                  value: rid
                - name: FEISHU_APP_ID
                  value: aid
                - name: FEISHU_APP_SECRET
                  value: act
              image: 'image'
              imagePullPolicy: Always
              name: mysql-diff
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 200m
                  memory: 128Mi
          dnsPolicy: ClusterFirst
          #imagePullSecrets:
          #  - name: gitlab-registry
          restartPolicy: OnFailure
          schedulerName: default-scheduler
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
